services:
  web:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    command: npm start
  api:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000