// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, ChangeUsernameData, ChangeUsernameErrors, ChangeUsernameResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetSkinByNameData, GetSkinByNameErrors, GetSkinByNameResponses, GetUserAvatarData, GetUserAvatarErrors, GetUserAvatarResponses, GetUserData, GetUserErrors, GetUserProfileData, GetUserProfileResponses, GetUserResponses, HealthCheckGetData, HealthCheckGetResponses, ListUsersData, ListUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, UploadSkinData, UploadSkinErrors, UploadSkinResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get User Profile
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>): RequestResult<GetUserProfileResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({ url: '/api/v1/user/me', ...options });

/**
 * Change Password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    url: '/api/v1/user/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change Username
 */
export const changeUsername = <ThrowOnError extends boolean = false>(options: Options<ChangeUsernameData, ThrowOnError>): RequestResult<ChangeUsernameResponses, ChangeUsernameErrors, ThrowOnError> => (options.client ?? client).post<ChangeUsernameResponses, ChangeUsernameErrors, ThrowOnError>({ url: '/api/v1/user/change-username', ...options });

/**
 * List Users
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({ url: '/api/v1/user/list', ...options });

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({ url: '/api/v1/user/{user_id}', ...options });

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/api/v1/user/{user_id}', ...options });

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Get Skin By Name
 */
export const getSkinByName = <ThrowOnError extends boolean = false>(options?: Options<GetSkinByNameData, ThrowOnError>): RequestResult<GetSkinByNameResponses, GetSkinByNameErrors, ThrowOnError> => (options?.client ?? client).get<GetSkinByNameResponses, GetSkinByNameErrors, ThrowOnError>({ url: '/api/v1/skin/', ...options });

/**
 * Get User Avatar
 */
export const getUserAvatar = <ThrowOnError extends boolean = false>(options?: Options<GetUserAvatarData, ThrowOnError>): RequestResult<GetUserAvatarResponses, GetUserAvatarErrors, ThrowOnError> => (options?.client ?? client).get<GetUserAvatarResponses, GetUserAvatarErrors, ThrowOnError>({ url: '/api/v1/skin/avatar', ...options });

/**
 * Upload Skin
 */
export const uploadSkin = <ThrowOnError extends boolean = false>(options: Options<UploadSkinData, ThrowOnError>): RequestResult<UploadSkinResponses, UploadSkinErrors, ThrowOnError> => (options.client ?? client).post<UploadSkinResponses, UploadSkinErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/skin/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Health Check
 */
export const healthCheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckGetData, ThrowOnError>): RequestResult<HealthCheckGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
