// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, ChangeUsernameData, ChangeUsernameErrors, ChangeUsernameResponses, CreateArchiveData, CreateArchiveErrors, CreateArchiveResponses, DeleteArchiveData, DeleteArchiveErrors, DeleteArchiveResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetArchiveData, GetArchiveErrors, GetArchiveResponses, GetModsData, GetModsResponses, GetServerConfigData, GetServerConfigResponses, GetServerStatusData, GetServerStatusResponses, GetSkinByNameData, GetSkinByNameErrors, GetSkinByNameResponses, GetStatsData, GetStatsResponses, GetUserAvatarData, GetUserAvatarErrors, GetUserAvatarResponses, GetUserData, GetUserErrors, GetUserProfileData, GetUserProfileResponses, GetUserResponses, HealthCheckGetData, HealthCheckGetResponses, ListArchivesData, ListArchivesResponses, ListUsersData, ListUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, SetUserStatusData, SetUserStatusErrors, SetUserStatusResponses, UpdateArchiveData, UpdateArchiveErrors, UpdateArchiveResponses, UpdateServerConfigData, UpdateServerConfigErrors, UpdateServerConfigResponses, UploadSkinData, UploadSkinErrors, UploadSkinResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get User Profile
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>): RequestResult<GetUserProfileResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({ url: '/api/v1/user/me', ...options });

/**
 * Change Password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    url: '/api/v1/user/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change Username
 */
export const changeUsername = <ThrowOnError extends boolean = false>(options: Options<ChangeUsernameData, ThrowOnError>): RequestResult<ChangeUsernameResponses, ChangeUsernameErrors, ThrowOnError> => (options.client ?? client).post<ChangeUsernameResponses, ChangeUsernameErrors, ThrowOnError>({
    url: '/api/v1/user/change-username',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Users
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({ url: '/api/v1/user/list', ...options });

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({ url: '/api/v1/user/{user_id}', ...options });

/**
 * Get User
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/api/v1/user/{user_id}', ...options });

/**
 * Set User Status
 */
export const setUserStatus = <ThrowOnError extends boolean = false>(options: Options<SetUserStatusData, ThrowOnError>): RequestResult<SetUserStatusResponses, SetUserStatusErrors, ThrowOnError> => (options.client ?? client).post<SetUserStatusResponses, SetUserStatusErrors, ThrowOnError>({
    url: '/api/v1/user/{user_id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Get Skin By Name
 */
export const getSkinByName = <ThrowOnError extends boolean = false>(options?: Options<GetSkinByNameData, ThrowOnError>): RequestResult<GetSkinByNameResponses, GetSkinByNameErrors, ThrowOnError> => (options?.client ?? client).get<GetSkinByNameResponses, GetSkinByNameErrors, ThrowOnError>({ url: '/api/v1/skin/', ...options });

/**
 * Get User Avatar
 */
export const getUserAvatar = <ThrowOnError extends boolean = false>(options?: Options<GetUserAvatarData, ThrowOnError>): RequestResult<GetUserAvatarResponses, GetUserAvatarErrors, ThrowOnError> => (options?.client ?? client).get<GetUserAvatarResponses, GetUserAvatarErrors, ThrowOnError>({ url: '/api/v1/skin/avatar', ...options });

/**
 * Upload Skin
 */
export const uploadSkin = <ThrowOnError extends boolean = false>(options: Options<UploadSkinData, ThrowOnError>): RequestResult<UploadSkinResponses, UploadSkinErrors, ThrowOnError> => (options.client ?? client).post<UploadSkinResponses, UploadSkinErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v1/skin/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get Stats
 */
export const getStats = <ThrowOnError extends boolean = false>(options?: Options<GetStatsData, ThrowOnError>): RequestResult<GetStatsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetStatsResponses, unknown, ThrowOnError>({ url: '/api/v1/admin/stats', ...options });

/**
 * Get Server Config
 */
export const getServerConfig = <ThrowOnError extends boolean = false>(options?: Options<GetServerConfigData, ThrowOnError>): RequestResult<GetServerConfigResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetServerConfigResponses, unknown, ThrowOnError>({ url: '/api/v1/admin/server', ...options });

/**
 * Update Server Config
 */
export const updateServerConfig = <ThrowOnError extends boolean = false>(options: Options<UpdateServerConfigData, ThrowOnError>): RequestResult<UpdateServerConfigResponses, UpdateServerConfigErrors, ThrowOnError> => (options.client ?? client).put<UpdateServerConfigResponses, UpdateServerConfigErrors, ThrowOnError>({
    url: '/api/v1/admin/server',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Mods
 *
 * Список модов из репозитория packwiz (см. ServerConfig.mods_repo_url).
 */
export const getMods = <ThrowOnError extends boolean = false>(options?: Options<GetModsData, ThrowOnError>): RequestResult<GetModsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetModsResponses, unknown, ThrowOnError>({ url: '/api/v1/admin/mods', ...options });

/**
 * Get Server Status
 *
 * Живой статус майнкрафт-сервера — реальный пинг по config.ip.
 */
export const getServerStatus = <ThrowOnError extends boolean = false>(options?: Options<GetServerStatusData, ThrowOnError>): RequestResult<GetServerStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetServerStatusResponses, unknown, ThrowOnError>({ url: '/api/v1/admin/status', ...options });

/**
 * Create Archive
 */
export const createArchive = <ThrowOnError extends boolean = false>(options: Options<CreateArchiveData, ThrowOnError>): RequestResult<CreateArchiveResponses, CreateArchiveErrors, ThrowOnError> => (options.client ?? client).post<CreateArchiveResponses, CreateArchiveErrors, ThrowOnError>({
    url: '/api/v1/admin/archive',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Archive
 */
export const deleteArchive = <ThrowOnError extends boolean = false>(options: Options<DeleteArchiveData, ThrowOnError>): RequestResult<DeleteArchiveResponses, DeleteArchiveErrors, ThrowOnError> => (options.client ?? client).delete<DeleteArchiveResponses, DeleteArchiveErrors, ThrowOnError>({ url: '/api/v1/admin/archive/{archive_id}', ...options });

/**
 * Update Archive
 */
export const updateArchive = <ThrowOnError extends boolean = false>(options: Options<UpdateArchiveData, ThrowOnError>): RequestResult<UpdateArchiveResponses, UpdateArchiveErrors, ThrowOnError> => (options.client ?? client).put<UpdateArchiveResponses, UpdateArchiveErrors, ThrowOnError>({
    url: '/api/v1/admin/archive/{archive_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Archives
 */
export const listArchives = <ThrowOnError extends boolean = false>(options?: Options<ListArchivesData, ThrowOnError>): RequestResult<ListArchivesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListArchivesResponses, unknown, ThrowOnError>({ url: '/api/v1/archive', ...options });

/**
 * Get Archive
 */
export const getArchive = <ThrowOnError extends boolean = false>(options: Options<GetArchiveData, ThrowOnError>): RequestResult<GetArchiveResponses, GetArchiveErrors, ThrowOnError> => (options.client ?? client).get<GetArchiveResponses, GetArchiveErrors, ThrowOnError>({ url: '/api/v1/archive/{archive_id}', ...options });

/**
 * Health Check
 */
export const healthCheckGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckGetData, ThrowOnError>): RequestResult<HealthCheckGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCheckGetResponses, unknown, ThrowOnError>({ url: '/', ...options });
