// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_skin_api_v1_skin_upload_post
 */
export type BodyUploadSkinApiV1SkinUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
    /**
     * Confirm Password
     */
    confirm_password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Role
     */
    role: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type GetUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUsernameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
    };
    url: '/api/v1/user/change-username';
};

export type ChangeUsernameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUsernameError = ChangeUsernameErrors[keyof ChangeUsernameErrors];

export type ChangeUsernameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/list';
};

export type ListUsersResponses = {
    /**
     * Response List Users Api V1 User List Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/user/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/user/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSkinByNameData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Uuid
         */
        uuid?: string | null;
    };
    url: '/api/v1/skin/';
};

export type GetSkinByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSkinByNameError = GetSkinByNameErrors[keyof GetSkinByNameErrors];

export type GetSkinByNameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserAvatarData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Uuid
         */
        uuid?: string | null;
    };
    url: '/api/v1/skin/avatar';
};

export type GetUserAvatarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserAvatarError = GetUserAvatarErrors[keyof GetUserAvatarErrors];

export type GetUserAvatarResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSkinData = {
    body: BodyUploadSkinApiV1SkinUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/skin/upload';
};

export type UploadSkinErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSkinError = UploadSkinErrors[keyof UploadSkinErrors];

export type UploadSkinResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
