// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ArchiveCreate
 */
export type ArchiveCreate = {
    /**
     * Name
     */
    name?: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Modloader
     */
    modLoader?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Files
     */
    files?: Array<ArchiveFileSchema>;
    /**
     * Screenshots
     */
    screenshots?: Array<string>;
};

/**
 * ArchiveFileSchema
 */
export type ArchiveFileSchema = {
    /**
     * Id
     */
    id?: number;
    /**
     * Name
     */
    name?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Size
     */
    size?: string;
    /**
     * Url
     */
    url?: string;
    [key: string]: unknown;
};

/**
 * ArchiveResponse
 */
export type ArchiveResponse = {
    /**
     * Name
     */
    name?: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Modloader
     */
    modLoader?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Files
     */
    files?: Array<ArchiveFileSchema>;
    /**
     * Screenshots
     */
    screenshots?: Array<string>;
    /**
     * Id
     */
    id: number;
};

/**
 * Body_upload_skin_api_v1_skin_upload_post
 */
export type BodyUploadSkinApiV1SkinUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
    /**
     * Confirm Password
     */
    confirm_password: string;
};

/**
 * ChangeUsernameRequest
 */
export type ChangeUsernameRequest = {
    /**
     * Username
     */
    username: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ModEntry
 *
 * Один мод из репозитория packwiz (одна запись на платформу/сторону).
 *
 * Формат приходит извне (packwiz export), поэтому допускаем лишние поля.
 */
export type ModEntry = {
    /**
     * Name
     */
    name?: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Filename
     */
    filename?: string;
    /**
     * Download Url
     */
    download_url?: string;
    /**
     * Page Url
     */
    page_url?: string;
    /**
     * Platform
     */
    platform?: string;
    /**
     * Side
     */
    side?: string;
    [key: string]: unknown;
};

/**
 * PlayerSample
 *
 * Игрок из sample-списка ответа Server List Ping.
 */
export type PlayerSample = {
    /**
     * Name
     */
    name?: string;
    /**
     * Uuid
     */
    uuid?: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ServerConfigSchema
 */
export type ServerConfigSchema = {
    /**
     * Ip
     */
    ip?: string;
    /**
     * Name
     */
    name?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Launchdate
     */
    launchDate?: string;
    /**
     * Modloader
     */
    modLoader?: string;
    /**
     * Modsrepourl
     */
    modsRepoUrl?: string;
    /**
     * Pinnedmods
     */
    pinnedMods?: Array<string>;
};

/**
 * ServerStatusResponse
 *
 * Живой статус майнкрафт-сервера (реальный пинг по config.ip).
 */
export type ServerStatusResponse = {
    /**
     * Online
     */
    online?: boolean;
    /**
     * Playersonline
     */
    playersOnline?: number;
    /**
     * Playersmax
     */
    playersMax?: number;
    /**
     * Latencyms
     */
    latencyMs?: number;
    /**
     * Version
     */
    version?: string;
    /**
     * Players
     */
    players?: Array<PlayerSample>;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    /**
     * Onlineplayers
     */
    onlinePlayers?: number;
    /**
     * Websiteusersnow
     */
    websiteUsersNow?: number;
    /**
     * Launcherdownloads
     */
    launcherDownloads?: number;
    /**
     * Websiteusersdaily
     */
    websiteUsersDaily?: number;
    /**
     * Websiteusersmonthly
     */
    websiteUsersMonthly?: number;
    /**
     * Totalregistered
     */
    totalRegistered?: number;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Role
     */
    role: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserStatusRequest
 */
export type UserStatusRequest = {
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/me';
};

export type GetUserProfileResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUsernameData = {
    body: ChangeUsernameRequest;
    path?: never;
    query?: never;
    url: '/api/v1/user/change-username';
};

export type ChangeUsernameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUsernameError = ChangeUsernameErrors[keyof ChangeUsernameErrors];

export type ChangeUsernameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user/list';
};

export type ListUsersResponses = {
    /**
     * Response List Users Api V1 User List Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/user/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/user/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type SetUserStatusData = {
    body: UserStatusRequest;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/user/{user_id}/status';
};

export type SetUserStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetUserStatusError = SetUserStatusErrors[keyof SetUserStatusErrors];

export type SetUserStatusResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type SetUserStatusResponse = SetUserStatusResponses[keyof SetUserStatusResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSkinByNameData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Uuid
         */
        uuid?: string | null;
    };
    url: '/api/v1/skin/';
};

export type GetSkinByNameErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSkinByNameError = GetSkinByNameErrors[keyof GetSkinByNameErrors];

export type GetSkinByNameResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserAvatarData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Name
         */
        name?: string | null;
        /**
         * Uuid
         */
        uuid?: string | null;
    };
    url: '/api/v1/skin/avatar';
};

export type GetUserAvatarErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserAvatarError = GetUserAvatarErrors[keyof GetUserAvatarErrors];

export type GetUserAvatarResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadSkinData = {
    body: BodyUploadSkinApiV1SkinUploadPost;
    path?: never;
    query?: never;
    url: '/api/v1/skin/upload';
};

export type UploadSkinErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadSkinError = UploadSkinErrors[keyof UploadSkinErrors];

export type UploadSkinResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats';
};

export type GetStatsResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetServerConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/server';
};

export type GetServerConfigResponses = {
    /**
     * Successful Response
     */
    200: ServerConfigSchema;
};

export type GetServerConfigResponse = GetServerConfigResponses[keyof GetServerConfigResponses];

export type UpdateServerConfigData = {
    body: ServerConfigSchema;
    path?: never;
    query?: never;
    url: '/api/v1/admin/server';
};

export type UpdateServerConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateServerConfigError = UpdateServerConfigErrors[keyof UpdateServerConfigErrors];

export type UpdateServerConfigResponses = {
    /**
     * Successful Response
     */
    200: ServerConfigSchema;
};

export type UpdateServerConfigResponse = UpdateServerConfigResponses[keyof UpdateServerConfigResponses];

export type GetModsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/mods';
};

export type GetModsResponses = {
    /**
     * Response Get Mods Api V1 Admin Mods Get
     *
     * Successful Response
     */
    200: Array<ModEntry>;
};

export type GetModsResponse = GetModsResponses[keyof GetModsResponses];

export type GetServerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/status';
};

export type GetServerStatusResponses = {
    /**
     * Successful Response
     */
    200: ServerStatusResponse;
};

export type GetServerStatusResponse = GetServerStatusResponses[keyof GetServerStatusResponses];

export type CreateArchiveData = {
    body: ArchiveCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/archive';
};

export type CreateArchiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateArchiveError = CreateArchiveErrors[keyof CreateArchiveErrors];

export type CreateArchiveResponses = {
    /**
     * Successful Response
     */
    201: ArchiveResponse;
};

export type CreateArchiveResponse = CreateArchiveResponses[keyof CreateArchiveResponses];

export type DeleteArchiveData = {
    body?: never;
    path: {
        /**
         * Archive Id
         */
        archive_id: number;
    };
    query?: never;
    url: '/api/v1/admin/archive/{archive_id}';
};

export type DeleteArchiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteArchiveError = DeleteArchiveErrors[keyof DeleteArchiveErrors];

export type DeleteArchiveResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteArchiveResponse = DeleteArchiveResponses[keyof DeleteArchiveResponses];

export type UpdateArchiveData = {
    body: ArchiveCreate;
    path: {
        /**
         * Archive Id
         */
        archive_id: number;
    };
    query?: never;
    url: '/api/v1/admin/archive/{archive_id}';
};

export type UpdateArchiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateArchiveError = UpdateArchiveErrors[keyof UpdateArchiveErrors];

export type UpdateArchiveResponses = {
    /**
     * Successful Response
     */
    200: ArchiveResponse;
};

export type UpdateArchiveResponse = UpdateArchiveResponses[keyof UpdateArchiveResponses];

export type ListArchivesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/archive';
};

export type ListArchivesResponses = {
    /**
     * Response List Archives Api V1 Archive Get
     *
     * Successful Response
     */
    200: Array<ArchiveResponse>;
};

export type ListArchivesResponse = ListArchivesResponses[keyof ListArchivesResponses];

export type GetArchiveData = {
    body?: never;
    path: {
        /**
         * Archive Id
         */
        archive_id: number;
    };
    query?: never;
    url: '/api/v1/archive/{archive_id}';
};

export type GetArchiveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArchiveError = GetArchiveErrors[keyof GetArchiveErrors];

export type GetArchiveResponses = {
    /**
     * Successful Response
     */
    200: ArchiveResponse;
};

export type GetArchiveResponse = GetArchiveResponses[keyof GetArchiveResponses];

export type HealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
