// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { changePassword, changeUsername, createArchive, deleteArchive, deleteUser, getArchive, getMods, getServerConfig, getServerStatus, getSkinByName, getStats, getUser, getUserAvatar, getUserProfile, healthCheckGet, listArchives, listUsers, login, logout, type Options, register, setUserStatus, updateArchive, updateServerConfig, uploadSkin } from '../sdk.gen';
import type { ChangePasswordData, ChangePasswordError, ChangeUsernameData, ChangeUsernameError, CreateArchiveData, CreateArchiveError, CreateArchiveResponse, DeleteArchiveData, DeleteArchiveError, DeleteArchiveResponse, DeleteUserData, DeleteUserError, DeleteUserResponse, GetArchiveData, GetArchiveError, GetArchiveResponse, GetModsData, GetModsResponse, GetServerConfigData, GetServerConfigResponse, GetServerStatusData, GetServerStatusResponse, GetSkinByNameData, GetSkinByNameError, GetStatsData, GetStatsResponse, GetUserAvatarData, GetUserAvatarError, GetUserData, GetUserError, GetUserProfileData, GetUserProfileResponse, GetUserResponse, HealthCheckGetData, ListArchivesData, ListArchivesResponse, ListUsersData, ListUsersResponse, LoginData, LoginError, LoginResponse, LogoutData, RegisterData, RegisterError, RegisterResponse, SetUserStatusData, SetUserStatusError, SetUserStatusResponse, UpdateArchiveData, UpdateArchiveError, UpdateArchiveResponse, UpdateServerConfigData, UpdateServerConfigError, UpdateServerConfigResponse, UploadSkinData, UploadSkinError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUserProfileQueryKey = (options?: Options<GetUserProfileData>) => createQueryKey('getUserProfile', options);

/**
 * Get User Profile
 */
export const getUserProfileOptions = (options?: Options<GetUserProfileData>) => queryOptions<GetUserProfileResponse, DefaultError, GetUserProfileResponse, ReturnType<typeof getUserProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserProfileQueryKey(options)
});

/**
 * Change Password
 */
export const changePasswordMutation = (options?: Partial<Options<ChangePasswordData>>): UseMutationOptions<unknown, ChangePasswordError, Options<ChangePasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, ChangePasswordError, Options<ChangePasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change Username
 */
export const changeUsernameMutation = (options?: Partial<Options<ChangeUsernameData>>): UseMutationOptions<unknown, ChangeUsernameError, Options<ChangeUsernameData>> => {
    const mutationOptions: UseMutationOptions<unknown, ChangeUsernameError, Options<ChangeUsernameData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changeUsername({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List Users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, DefaultError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * Delete User
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<DeleteUserResponse, DeleteUserError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<DeleteUserResponse, DeleteUserError, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get User
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Set User Status
 */
export const setUserStatusMutation = (options?: Partial<Options<SetUserStatusData>>): UseMutationOptions<SetUserStatusResponse, SetUserStatusError, Options<SetUserStatusData>> => {
    const mutationOptions: UseMutationOptions<SetUserStatusResponse, SetUserStatusError, Options<SetUserStatusData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setUserStatus({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSkinByNameQueryKey = (options?: Options<GetSkinByNameData>) => createQueryKey('getSkinByName', options);

/**
 * Get Skin By Name
 */
export const getSkinByNameOptions = (options?: Options<GetSkinByNameData>) => queryOptions<unknown, GetSkinByNameError, unknown, ReturnType<typeof getSkinByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSkinByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSkinByNameQueryKey(options)
});

export const getUserAvatarQueryKey = (options?: Options<GetUserAvatarData>) => createQueryKey('getUserAvatar', options);

/**
 * Get User Avatar
 */
export const getUserAvatarOptions = (options?: Options<GetUserAvatarData>) => queryOptions<unknown, GetUserAvatarError, unknown, ReturnType<typeof getUserAvatarQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAvatar({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAvatarQueryKey(options)
});

/**
 * Upload Skin
 */
export const uploadSkinMutation = (options?: Partial<Options<UploadSkinData>>): UseMutationOptions<unknown, UploadSkinError, Options<UploadSkinData>> => {
    const mutationOptions: UseMutationOptions<unknown, UploadSkinError, Options<UploadSkinData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadSkin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStatsQueryKey = (options?: Options<GetStatsData>) => createQueryKey('getStats', options);

/**
 * Get Stats
 */
export const getStatsOptions = (options?: Options<GetStatsData>) => queryOptions<GetStatsResponse, DefaultError, GetStatsResponse, ReturnType<typeof getStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStatsQueryKey(options)
});

export const getServerConfigQueryKey = (options?: Options<GetServerConfigData>) => createQueryKey('getServerConfig', options);

/**
 * Get Server Config
 */
export const getServerConfigOptions = (options?: Options<GetServerConfigData>) => queryOptions<GetServerConfigResponse, DefaultError, GetServerConfigResponse, ReturnType<typeof getServerConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getServerConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getServerConfigQueryKey(options)
});

/**
 * Update Server Config
 */
export const updateServerConfigMutation = (options?: Partial<Options<UpdateServerConfigData>>): UseMutationOptions<UpdateServerConfigResponse, UpdateServerConfigError, Options<UpdateServerConfigData>> => {
    const mutationOptions: UseMutationOptions<UpdateServerConfigResponse, UpdateServerConfigError, Options<UpdateServerConfigData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateServerConfig({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getModsQueryKey = (options?: Options<GetModsData>) => createQueryKey('getMods', options);

/**
 * Get Mods
 *
 * Список модов из репозитория packwiz (см. ServerConfig.mods_repo_url).
 */
export const getModsOptions = (options?: Options<GetModsData>) => queryOptions<GetModsResponse, DefaultError, GetModsResponse, ReturnType<typeof getModsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMods({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getModsQueryKey(options)
});

export const getServerStatusQueryKey = (options?: Options<GetServerStatusData>) => createQueryKey('getServerStatus', options);

/**
 * Get Server Status
 *
 * Живой статус майнкрафт-сервера — реальный пинг по config.ip.
 */
export const getServerStatusOptions = (options?: Options<GetServerStatusData>) => queryOptions<GetServerStatusResponse, DefaultError, GetServerStatusResponse, ReturnType<typeof getServerStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getServerStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getServerStatusQueryKey(options)
});

/**
 * Create Archive
 */
export const createArchiveMutation = (options?: Partial<Options<CreateArchiveData>>): UseMutationOptions<CreateArchiveResponse, CreateArchiveError, Options<CreateArchiveData>> => {
    const mutationOptions: UseMutationOptions<CreateArchiveResponse, CreateArchiveError, Options<CreateArchiveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createArchive({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Archive
 */
export const deleteArchiveMutation = (options?: Partial<Options<DeleteArchiveData>>): UseMutationOptions<DeleteArchiveResponse, DeleteArchiveError, Options<DeleteArchiveData>> => {
    const mutationOptions: UseMutationOptions<DeleteArchiveResponse, DeleteArchiveError, Options<DeleteArchiveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteArchive({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Archive
 */
export const updateArchiveMutation = (options?: Partial<Options<UpdateArchiveData>>): UseMutationOptions<UpdateArchiveResponse, UpdateArchiveError, Options<UpdateArchiveData>> => {
    const mutationOptions: UseMutationOptions<UpdateArchiveResponse, UpdateArchiveError, Options<UpdateArchiveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateArchive({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listArchivesQueryKey = (options?: Options<ListArchivesData>) => createQueryKey('listArchives', options);

/**
 * List Archives
 */
export const listArchivesOptions = (options?: Options<ListArchivesData>) => queryOptions<ListArchivesResponse, DefaultError, ListArchivesResponse, ReturnType<typeof listArchivesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listArchives({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listArchivesQueryKey(options)
});

export const getArchiveQueryKey = (options: Options<GetArchiveData>) => createQueryKey('getArchive', options);

/**
 * Get Archive
 */
export const getArchiveOptions = (options: Options<GetArchiveData>) => queryOptions<GetArchiveResponse, GetArchiveError, GetArchiveResponse, ReturnType<typeof getArchiveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getArchive({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getArchiveQueryKey(options)
});

export const healthCheckGetQueryKey = (options?: Options<HealthCheckGetData>) => createQueryKey('healthCheckGet', options);

/**
 * Health Check
 */
export const healthCheckGetOptions = (options?: Options<HealthCheckGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckGetQueryKey(options)
});
