// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { changePassword, changeUsername, deleteUser, getSkinByName, getUser, getUserAvatar, getUserProfile, healthCheckGet, listUsers, login, logout, type Options, register, uploadSkin } from '../sdk.gen';
import type { ChangePasswordData, ChangePasswordError, ChangeUsernameData, ChangeUsernameError, DeleteUserData, DeleteUserError, GetSkinByNameData, GetSkinByNameError, GetUserAvatarData, GetUserAvatarError, GetUserData, GetUserError, GetUserProfileData, GetUserProfileResponse, GetUserResponse, HealthCheckGetData, ListUsersData, ListUsersResponse, LoginData, LoginError, LoginResponse, LogoutData, RegisterData, RegisterError, RegisterResponse, UploadSkinData, UploadSkinError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUserProfileQueryKey = (options?: Options<GetUserProfileData>) => createQueryKey('getUserProfile', options);

/**
 * Get User Profile
 */
export const getUserProfileOptions = (options?: Options<GetUserProfileData>) => queryOptions<GetUserProfileResponse, DefaultError, GetUserProfileResponse, ReturnType<typeof getUserProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserProfileQueryKey(options)
});

/**
 * Change Password
 */
export const changePasswordMutation = (options?: Partial<Options<ChangePasswordData>>): UseMutationOptions<unknown, ChangePasswordError, Options<ChangePasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, ChangePasswordError, Options<ChangePasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changePassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Change Username
 */
export const changeUsernameMutation = (options?: Partial<Options<ChangeUsernameData>>): UseMutationOptions<unknown, ChangeUsernameError, Options<ChangeUsernameData>> => {
    const mutationOptions: UseMutationOptions<unknown, ChangeUsernameError, Options<ChangeUsernameData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await changeUsername({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List Users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => queryOptions<ListUsersResponse, DefaultError, ListUsersResponse, ReturnType<typeof listUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listUsersQueryKey(options)
});

/**
 * Delete User
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get User
 */
export const getUserOptions = (options: Options<GetUserData>) => queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserQueryKey(options)
});

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, RegisterError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSkinByNameQueryKey = (options?: Options<GetSkinByNameData>) => createQueryKey('getSkinByName', options);

/**
 * Get Skin By Name
 */
export const getSkinByNameOptions = (options?: Options<GetSkinByNameData>) => queryOptions<unknown, GetSkinByNameError, unknown, ReturnType<typeof getSkinByNameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSkinByName({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSkinByNameQueryKey(options)
});

export const getUserAvatarQueryKey = (options?: Options<GetUserAvatarData>) => createQueryKey('getUserAvatar', options);

/**
 * Get User Avatar
 */
export const getUserAvatarOptions = (options?: Options<GetUserAvatarData>) => queryOptions<unknown, GetUserAvatarError, unknown, ReturnType<typeof getUserAvatarQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAvatar({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAvatarQueryKey(options)
});

/**
 * Upload Skin
 */
export const uploadSkinMutation = (options?: Partial<Options<UploadSkinData>>): UseMutationOptions<unknown, UploadSkinError, Options<UploadSkinData>> => {
    const mutationOptions: UseMutationOptions<unknown, UploadSkinError, Options<UploadSkinData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadSkin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthCheckGetQueryKey = (options?: Options<HealthCheckGetData>) => createQueryKey('healthCheckGet', options);

/**
 * Health Check
 */
export const healthCheckGetOptions = (options?: Options<HealthCheckGetData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof healthCheckGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheckGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckGetQueryKey(options)
});
